# Generated by Django 6.0.5 on 2026-05-12 03:42

from django.db import migrations, models


def migrate_to_shared_course_quizzes(apps, schema_editor):
    Course = apps.get_model('lms', 'Course')
    Quiz = apps.get_model('lms', 'Quiz')
    UserQuizAttempt = apps.get_model('lms', 'UserQuizAttempt')

    for attempt in UserQuizAttempt.objects.select_related('quiz'):
        attempt.attempt_type = attempt.quiz.quiz_type
        attempt.save(update_fields=['attempt_type'])

    for course in Course.objects.all():
        canonical, _ = Quiz.objects.get_or_create(course=course, quiz_type='post')
        legacy_pre = Quiz.objects.filter(course=course, quiz_type='pre').first()

        if legacy_pre and not canonical.questions.exists() and legacy_pre.questions.exists():
            legacy_pre.questions.update(quiz=canonical)

        if legacy_pre:
            UserQuizAttempt.objects.filter(quiz=legacy_pre).update(quiz=canonical)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_background',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_backgrounds/', verbose_name='ภาพพื้นหลังใบประกาศนียบัตร'),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='attempt_type',
            field=models.CharField(choices=[('pre', 'แบบทดสอบก่อนเรียน'), ('post', 'แบบทดสอบหลังเรียน')], default='post', max_length=4, verbose_name='ประเภทการสอบ'),
        ),
        migrations.RunPython(migrate_to_shared_course_quizzes, noop_reverse),
    ]
