# Generated by Django 6.0.5 on 2026-05-12 08:23

import uuid
from datetime import datetime

from django.db import migrations, models


def populate_certificate_serial_numbers(apps, schema_editor):
    Certificate = apps.get_model('lms', 'Certificate')
    year_be = datetime.now().year + 543
    for certificate in Certificate.objects.filter(serial_number__isnull=True):
        certificate.serial_number = f'CERT-{year_be}-{uuid.uuid4().hex[:6].upper()}'
        certificate.save(update_fields=['serial_number'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_certificate_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_threshold',
            field=models.PositiveIntegerField(default=70, help_text='คะแนนขั้นต่ำที่ผ่าน (%)'),
        ),
        migrations.RunPython(populate_certificate_serial_numbers, noop_reverse),
        migrations.AlterField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
