# Generated by Django 6.0.5 on 2026-05-12 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_certificate_serial_number_course_pass_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, help_text='LINE User ID สำหรับส่ง Push Notification', max_length=50, verbose_name='LINE User ID'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('course_complete', 'Course Completed'), ('quiz_pass', 'Quiz Passed'), ('quiz_fail', 'Quiz Failed'), ('certificate_issued', 'Certificate Issued'), ('staff_course_create', 'Course Created'), ('staff_course_edit', 'Course Edited'), ('staff_course_delete', 'Course Deleted'), ('staff_user_create', 'User Created'), ('bulk_user_import', 'Bulk User Import')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
